Update server readme
pi-apps/pailot-for-pi pull request #48
Opened 2023-02-08 23:36 UTC by Saneeitas

2023-02-09 08:54 UTC, vyktoremario commented on server/README.md
> +```TypeScript
This should not be typescript. It is not a typescript code.
It is a shell or bash command.

2023-02-09 08:54 UTC, vyktoremario commented on server/README.md
> +```TypeScript
Same as above

2023-02-09 08:55 UTC, vyktoremario commented on server/README.md
> +```TypeScript
Same as above

2023-02-09 08:55 UTC, vyktoremario commented on server/README.md
> +```TypeScript
Same as above

2023-02-09 08:56 UTC, vyktoremario commented on server/README.md
> + "http://localhost:3333"
This is not supposed to be in a fence.

2023-02-09 08:57 UTC, vyktoremario requested changes
I left some comments.
Please fix the comment in this PR. Stop closing PR to fix comments

2023-02-09 13:13 UTC, Saneeitas commented on server/README.md
> + "http://localhost:3333"
Okay I Will do that

2023-02-10 13:25 UTC, vyktoremario approved these changes

2023-02-10 13:25 UTC, merged